//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_CncFlags 
  {
    CHMETH *pMeth;
    CncFlags dData;
    SVRDSC *pDsc;
  } SvrCh_CncFlags;

typedef struct CltCh_CncFlags 
  {
    struct SvrCh_CncFlags *pCh;
    CncFlags dData;
    SVRCHCMD *pCmd;
  } CltCh_CncFlags;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_FeSetup 
  {
    CHMETH *pMeth;
    FeSetup dData;
    SVRDSC *pDsc;
  } SvrCh_FeSetup;

typedef struct CltCh_FeSetup 
  {
    struct SvrCh_FeSetup *pCh;
    FeSetup dData;
    SVRCHCMD *pCmd;
  } CltCh_FeSetup;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_IO_State 
  {
    CHMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrCh_IO_State;

typedef struct CltCh_IO_State 
  {
    struct SvrCh_IO_State *pCh;
    IO_State dData;
    SVRCHCMD *pCmd;
  } CltCh_IO_State;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd__SerLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLib *pCmd;
  } CltChCmd__SerLib;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct SvrChCmd_HDINT 
  {
    CMDMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_HDINT;

typedef struct CltChCmd__SysDateTime 
  {
    struct SvrChCmd_HDINT *pCh;
    HDINT dData;
    _SysDateTime *pCmd;
  } CltChCmd__SysDateTime;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd__VaranCanLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _VaranCanLib *pCmd;
  } CltChCmd__VaranCanLib;

typedef struct CltChCmd__VaranCanLibOS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _VaranCanLibOS *pCmd;
  } CltChCmd__VaranCanLibOS;

typedef struct CltChCmd__VaranSerLibOS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _VaranSerLibOS *pCmd;
  } CltChCmd__VaranSerLibOS;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct CltChCmd_CAICIOAInputChannel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CAICIOAInputChannel *pCmd;
  } CltChCmd_CAICIOAInputChannel;

typedef struct CltChCmd_CDias2DataMover 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CDias2DataMover *pCmd;
  } CltChCmd_CDias2DataMover;

typedef struct CltChCmd_CIOOutputChannel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CIOOutputChannel *pCmd;
  } CltChCmd_CIOOutputChannel;

typedef struct CltChCmd_Controller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Controller *pCmd;
  } CltChCmd_Controller;

typedef struct CltChCmd_Dias2DataMover 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Dias2DataMover *pCmd;
  } CltChCmd_Dias2DataMover;

typedef struct CltChCmd_DiasMaster 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMaster *pCmd;
  } CltChCmd_DiasMaster;

typedef struct CltChCmd_DiasMasterC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterC *pCmd;
  } CltChCmd_DiasMasterC;

typedef struct CltChCmd_DiasMasterPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterPostScan *pCmd;
  } CltChCmd_DiasMasterPostScan;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_easyFileHandling 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    easyFileHandling *pCmd;
  } CltChCmd_easyFileHandling;

typedef struct CltChCmd_EEPROM 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EEPROM *pCmd;
  } CltChCmd_EEPROM;

typedef struct CltChCmd_File_IO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    File_IO *pCmd;
  } CltChCmd_File_IO;

typedef struct CltChCmd_FileBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    FileBase *pCmd;
  } CltChCmd_FileBase;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base *pCmd;
  } CltChCmd_Hub_Base;

typedef struct CltChCmd_Hub_Base_Root 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base_Root *pCmd;
  } CltChCmd_Hub_Base_Root;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct CltChCmd_HwBase 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    HwBase *pCmd;
  } CltChCmd_HwBase;

typedef struct CltChCmd_HwBaseCDIAS 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    HwBaseCDIAS *pCmd;
  } CltChCmd_HwBaseCDIAS;

typedef struct CltChCmd_HwControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControl *pCmd;
  } CltChCmd_HwControl;

typedef struct CltChCmd_HwControlBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControlBase *pCmd;
  } CltChCmd_HwControlBase;

typedef struct CltChCmd_HWRtPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWRtPostScan *pCmd;
  } CltChCmd_HWRtPostScan;

typedef struct CltChCmd_I2CCDIAS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    I2CCDIAS *pCmd;
  } CltChCmd_I2CCDIAS;

typedef struct CltChCmd_LoadSaveData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    LoadSaveData *pCmd;
  } CltChCmd_LoadSaveData;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_RamFile 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamFile *pCmd;
  } CltChCmd_RamFile;

typedef struct CltChCmd_Reference 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Reference *pCmd;
  } CltChCmd_Reference;

typedef struct CltChCmd_SafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyManager *pCmd;
  } CltChCmd_SafetyManager;

typedef struct CltChCmd_SdiasHubBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasHubBase *pCmd;
  } CltChCmd_SdiasHubBase;

typedef struct SvrChCmd_t_e_VaranErrors 
  {
    CMDMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrChCmd_t_e_VaranErrors;

typedef struct CltChCmd_SdiasManager 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasManager *pCmd;
  } CltChCmd_SdiasManager;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringRAM 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringRAM *pCmd;
  } CltChCmd_StringRAM;

typedef struct CltChCmd_SyncCall 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    SyncCall *pCmd;
  } CltChCmd_SyncCall;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_t_e_VaranErrors 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SVRCHCMD *pCmd;
  } CltChCmd_t_e_VaranErrors;

typedef struct CltChCmd_TellerClass_Teller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TellerClass_Teller *pCmd;
  } CltChCmd_TellerClass_Teller;

typedef struct CltChCmd_ToolcatHandling 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ToolcatHandling *pCmd;
  } CltChCmd_ToolcatHandling;

typedef struct CltChCmd_Varan_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_Base *pCmd;
  } CltChCmd_Varan_Base;

typedef struct CltChCmd_Varan_Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Varan_Can *pCmd;
  } CltChCmd_Varan_Can;

typedef struct CltChCmd_Varan_DataMover 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_DataMover *pCmd;
  } CltChCmd_Varan_DataMover;

typedef struct CltChCmd_VaranManager_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManager_Base *pCmd;
  } CltChCmd_VaranManager_Base;

typedef struct CltChCmd_VaranManagerPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManagerPostScan *pCmd;
  } CltChCmd_VaranManagerPostScan;

typedef struct CltChCmd_WatchdogDias 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    WatchdogDias *pCmd;
  } CltChCmd_WatchdogDias;

typedef struct CltChCmd_WisFilter 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    WisFilter *pCmd;
  } CltChCmd_WisFilter;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct SvrCh_SafetyConfigStateType 
  {
    CHMETH *pMeth;
    SafetyConfigStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SafetyConfigStateType;

typedef struct SvrCh_t_e_VaranErrors 
  {
    CHMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_VaranErrors;

typedef struct SvrCh_tDoosnaam 
  {
    CHMETH *pMeth;
    tDoosnaam dData;
    SVRDSC *pDsc;
  } SvrCh_tDoosnaam;

typedef struct SvrCh_tJamStatus 
  {
    CHMETH *pMeth;
    tJamStatus dData;
    SVRDSC *pDsc;
  } SvrCh_tJamStatus;

typedef struct SvrCh_tModel 
  {
    CHMETH *pMeth;
    tModel dData;
    SVRDSC *pDsc;
  } SvrCh_tModel;

typedef struct SvrCh_tSectie 
  {
    CHMETH *pMeth;
    tSectie dData;
    SVRDSC *pDsc;
  } SvrCh_tSectie;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct SvrChCmd_CNCCommandStatus 
  {
    CMDMETH *pMeth;
    CNCCommandStatus dData;
    SVRDSC *pDsc;
  } SvrChCmd_CNCCommandStatus;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

