//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  _CNC_DYN_SWLIMITS :  //! <Type Comment="Dynamic software end positions" Name="_CNC_DYN_SWLIMITS"/>
  (
    _DynSWLimitMin,  //! <Type Comment="Choose minimum dynamic position" Name="_CNC_DYN_SWLIMITS._DynSWLimitMin"/>
    _DynSWLimitMax  //! <Type Comment="Choose maximum dynamic position" Name="_CNC_DYN_SWLIMITS._DynSWLimitMax"/>
  )$UDINT;
  _LMCAXIS_CONTROLBITS : BDINT  //! <Type Comment="Control-Bits" Name="_LMCAXIS_CONTROLBITS"/>
  [
    1 SetPowerOn,  //! <Type Comment="Set if the clients &quot;LMCController&quot; and &quot;ActPosition&quot; are not connected or &#13;&#10;the axis is active" Name="_LMCAXIS_CONTROLBITS.SetPowerOn"/>
    2 SetFollowMode,  //! <Type Comment="Set if the axis is in operationmode: &quot;FOLLOW_LMCAXIS&quot;" Name="_LMCAXIS_CONTROLBITS.SetFollowMode"/>
  ];
  _LMCAXIS_ERROR : BDINT  //! <Type Comment="Error-Bits" Name="_LMCAXIS_ERROR"/>
  [
    1 HwError,  //! <Type Comment="Set if a general Hardware-Error occured" Name="_LMCAXIS_ERROR.HwError"/>
    2 SwMinError,  //! <Type Comment="Set if the Software-Endswitch Minimum is active" Name="_LMCAXIS_ERROR.SwMinError"/>
    3 SwMaxError,  //! <Type Comment="Set if the Software-Endswitch Maximum is active" Name="_LMCAXIS_ERROR.SwMaxError"/>
    4 HwMinError,  //! <Type Comment="Set if the Hardware-Endswitch Minimum is active" Name="_LMCAXIS_ERROR.HwMinError"/>
    5 HwMaxError,  //! <Type Comment="Set if the Hardware-Endswitch Maximum is active" Name="_LMCAXIS_ERROR.HwMaxError"/>
    6 ReferenceError,  //! <Type Comment="Set if an error occured during the reference-run" Name="_LMCAXIS_ERROR.ReferenceError"/>
    7 ContouringError,  //! <Type Comment="Set if a tracking-error occured" Name="_LMCAXIS_ERROR.ContouringError"/>
    8 ActPosError,  //! <Type Comment="Set if the Hardware-Position is invalid" Name="_LMCAXIS_ERROR.ActPosError"/>
    9 AbsOffsetError,  //! <Type Comment="Set if an Offset-Error occured" Name="_LMCAXIS_ERROR.AbsOffsetError"/>
    10 OverFlowError,  //! <Type Comment="Set if a Position-Overflow occured" Name="_LMCAXIS_ERROR.OverFlowError"/>
    11 EmergencyError,  //! <Type Comment="Set if the _LMCSafety.Emergency is active" Name="_LMCAXIS_ERROR.EmergencyError"/>
    12 ResolutionError,  //! <Type Comment="Set if the Resolution causes an overflow error&#13;&#10;" Name="_LMCAXIS_ERROR.ResolutionError"/>
    16 GlobErr,  //! <Type Comment="Set if a global error is active" Name="_LMCAXIS_ERROR.GlobErr"/>
  ];
  _LMCAXIS_STATUS : BDINT  //! <Type Comment="Status-Bits of the axis" Name="_LMCAXIS_STATUS"/>
  [
    1 PowerOn,  //! <Type Comment="Set if axis is activated" Name="_LMCAXIS_STATUS.PowerOn"/>
    2 IsReferenced,  //! <Type Comment="Set if axis is referenced" Name="_LMCAXIS_STATUS.IsReferenced"/>
    3 InPosition,  //! <Type Comment="Set if axis is in correct position" Name="_LMCAXIS_STATUS.InPosition"/>
    4 FiltRdy,  //! <Type Comment="Set if axis is in correct position an the jerkfilter is ready" Name="_LMCAXIS_STATUS.FiltRdy"/>
    5 Decell,  //! <Type Comment="Set if axis is braking" Name="_LMCAXIS_STATUS.Decell"/>
    6 PosLimActive,  //! <Type Comment="Set if axis has reached one of its endpositions" Name="_LMCAXIS_STATUS.PosLimActive"/>
    7 SetFlg,  //! <Type Comment="Set by calling one of the functions: SetPosition or ReferenceAxis&#13;&#10;Reset if the axis is activated" Name="_LMCAXIS_STATUS.SetFlg"/>
    8 EnLesFlg,  //! <Type Comment="Set if the axis moves endless / infinitely" Name="_LMCAXIS_STATUS.EnLesFlg"/>
    9 DirFlg,  //! <Type Comment="Set if the axis moves in negative direction - speed is negative" Name="_LMCAXIS_STATUS.DirFlg"/>
    10 EmergStop,  //! <Type Comment="Set if the axis stops because an error occured or the axis is deactivated" Name="_LMCAXIS_STATUS.EmergStop"/>
    11 Overflow,  //! <Type Comment="Set if a position-overflow occured" Name="_LMCAXIS_STATUS.Overflow"/>
    12 MasterLock,  //! <Type Comment="Set if the slave-axis is coupled onto a master-axis" Name="_LMCAXIS_STATUS.MasterLock"/>
    13 DirLock,  //! <Type Comment="the direction is locked&#13;&#10;(because of HWMin, HWMax&#13;&#10; or by PowerOnMode)" Name="_LMCAXIS_STATUS.DirLock"/>
    14 DynSwLimit,
    15 ActDirFlg,  //! <Type Comment="Set if the speed of the axis is negative" Name="_LMCAXIS_STATUS.ActDirFlg"/>
    16 HandFlg,  //! <Type Comment="Set if one of the functions: PowerOff or MoveHand is called" Name="_LMCAXIS_STATUS.HandFlg"/>
    17 ModuloFlg,  //! <Type Comment="Set if the axis is defined as a modulo-axis" Name="_LMCAXIS_STATUS.ModuloFlg"/>
    18 NCMotion,  //! <Type Comment="Set if the axis is in NC postion mode: &quot;_NCPositioning&quot;" Name="_LMCAXIS_STATUS.NCMotion"/>
    19 NoActPosMeth,  //! <Type Comment="Set if axis is in &quot;SimulateMode&quot; of the client &quot;ActPosition&quot; is not connected" Name="_LMCAXIS_STATUS.NoActPosMeth"/>
    20 NoControlMeth,  //! <Type Comment="Set if axis is in &quot;SimulateMode&quot; of the client &quot;LMCController&quot; is not connected" Name="_LMCAXIS_STATUS.NoControlMeth"/>
    21 NoRefMeth,  //! <Type Comment="Set if the client &quot;LMCReference&quot; is not connected or&#13;&#10;the function &quot;CheckConnection&quot; returns &quot;FALSE&quot; or&#13;&#10;the client &quot;ActPosition&quot; is not connected" Name="_LMCAXIS_STATUS.NoRefMeth"/>
    22 NoActPosChk,  //! <Type Comment="Set if the client LMCSafety is connected and the function &quot;ChkHWReadyConnect&quot; returns &quot;FALSE&quot; or&#13;&#10;the client LMCSafety is not connected or&#13;&#10;the SimulateMode is active" Name="_LMCAXIS_STATUS.NoActPosChk"/>
    23 NoPreRtWork,  //! <Type Comment="Set if the client &quot;LMCPreRtWorkTrigger&quot; is not connected" Name="_LMCAXIS_STATUS.NoPreRtWork"/>
    24 NoPostRtWork,  //! <Type Comment="Set if the client &quot;LMCPostRtWorkTrigger&quot; is not connected" Name="_LMCAXIS_STATUS.NoPostRtWork"/>
  ];
  _LMCCONTROLLERTYPE :
  (
    _LMCNOCONTROLLER,  //! <Type Comment="no controller" Name="_LMCCONTROLLERTYPE._LMCNOCONTROLLER"/>
    _LMCUSERCONTROLLER,  //! <Type Comment="user defined controller" Name="_LMCCONTROLLERTYPE._LMCUSERCONTROLLER"/>
    _LMCDUMMYCONTROLLER,  //! <Type Comment="DummyController" Name="_LMCCONTROLLERTYPE._LMCDUMMYCONTROLLER"/>
    _LMCHYDROCONTROLLER,  //! <Type Comment="HydroController" Name="_LMCCONTROLLERTYPE._LMCHYDROCONTROLLER"/>
    _LMCKV_CONTROLLER,  //! <Type Comment="KV_Controller" Name="_LMCCONTROLLERTYPE._LMCKV_CONTROLLER"/>
    _LMCNCCONTROLLER,  //! <Type Comment="NCController" Name="_LMCCONTROLLERTYPE._LMCNCCONTROLLER"/>
    _LMCPOSCONTROLLER,  //! <Type Comment="PosController" Name="_LMCCONTROLLERTYPE._LMCPOSCONTROLLER"/>
    _LMCDRIVEPOSONTROL  //! <Type Comment="DrivePosController" Name="_LMCCONTROLLERTYPE._LMCDRIVEPOSONTROL"/>
  )$UDINT;
#pragma pack(push, 1)
  Aansturing : STRUCT
    StotAan : ARRAY [0..10] OF DINT;
    StotUit : ARRAY [0..10] OF DINT;
    ScorAan : ARRAY [0..10] OF DINT;
    ScorUit : ARRAY [0..10] OF DINT;
    ScorBepaalAan : ARRAY [0..10] OF DINT;
    ScorBepaalUit : ARRAY [0..10] OF DINT;
    SExtraBox : DINT;
    SPosbuffer : ARRAY [0..10] OF DINT;
    Error : ARRAY [0..10] OF DINT;
    i : DINT;
    CaseAansturing : ARRAY [0..10] OF DINT;
    CaseAansturing2 : ARRAY [0..10] OF DINT;
    Offset : ARRAY [0..10] OF DINT;
    CaseRing : ARRAY [0..10] OF DINT;
    Spos : ARRAY [0..10] OF DINT;
    wrpoint : ARRAY [0..10] OF DINT;
    rdpoint : ARRAY [0..10] OF DINT;
    Senpos : ARRAY [0..10] OF DINT;
    Dooslengte : ARRAY [0..10] OF DINT;
    Din : ARRAY [0..10] OF DINT;
    Scoruiteerst : ARRAY [0..10] OF DINT;
    Testaaneerst : ARRAY [0..10] OF DINT;
    ii : DINT;
    UpdateConv : ARRAY [0..10] OF DINT;
    conveyor : ARRAY [0..10] OF DINT;
    ConveyorLoper : ARRAY [0..10] OF DINT;
    ConveyorCase : ARRAY [0..10] OF DINT;
    ConveyorPosdoos : ARRAY [0..10] OF DINT;
    ConveyorPosDoosNew : ARRAY [0..10] OF DINT;
    iii : DINT;
    iiii : DINT;
    Out : ARRAY [0..10] OF DINT;
    PakketWijzer : ARRAY [0..10] OF DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  AxisRef : STRUCT
    Speed : DINT;  //! <Type Comment="Reference speed" Name="AxisRef.Speed"/>
    Accel : DINT;  //! <Type Comment="Reference acceleration" Name="AxisRef.Accel"/>
    Stat : DINT;  //! <Type Comment="Reference status ( error or ready )" Name="AxisRef.Stat"/>
    LatchPosRef : DINT;  //! <Type Comment="External position [incr] used in mode &quot;RefLatchPos&quot;" Name="AxisRef.LatchPosRef"/>
  END_STRUCT;
#pragma pack(pop)
  BackFolder :
  (
    Opstarten:=13,
    IdleFase,
    EnableFase,
    HomeFase,
    LinupFase,
    SyncFase,
    NC_Production0,
    NC_Production1,
    NC_Production2,
    NC_Production3,
    NC_Production35,
    NC_Production4,
    NC_Production5,
    NC_Production6
  )$UDINT;
  CNCCommandStatus :
  (
    PassiveCNC,
    IdleCNC,
    MoveCNC,
    StopedCNC,
    LockedCNC,
    RefGoCNC,
    RefRunCNC,
    RefStopCNC,
    TunePosCNC,
    TuneNegCNC,
    ErrorCNC
  )$UDINT;
  CncFlags : BDINT
  [
    1 HwError,  //! <Type Comment="Hardware error Flag" Name="CncFlags.HwError"/>
    2 SwMin,  //! <Type Comment="Software endswitch minimum active" Name="CncFlags.SwMin"/>
    3 SwMax,  //! <Type Comment="Software endswitch maximum active" Name="CncFlags.SwMax"/>
    4 v_error,  //! <Type Comment="velocity setting error" Name="CncFlags.v_error"/>
    5 a_error,  //! <Type Comment="Acceleration / deceleration setting error" Name="CncFlags.a_error"/>
    6 ContrOff,  //! <Type Comment="position controller off" Name="CncFlags.ContrOff"/>
    7 NoRef,  //! <Type Comment="no position reference" Name="CncFlags.NoRef"/>
    8 DragLim,  //! <Type Comment="contouring error" Name="CncFlags.DragLim"/>
    9 ComandErr,  //! <Type Comment="Command is not exepted" Name="CncFlags.ComandErr"/>
    10 ActPosError,  //! <Type Comment="invalid position of the hardware" Name="CncFlags.ActPosError"/>
    11 IsNotControlling,  //! <Type Comment="wake and shake is active" Name="CncFlags.IsNotControlling"/>
    12 Follow,
    13 OverFlowError,
    16 GlobErr,  //! <Type Comment="Any other errors is active" Name="CncFlags.GlobErr"/>
  ];
#pragma pack(push, 1)
  CNCInternalStruct : STRUCT
    ptrExt : ^DINT;
    ptrInt : ^DINT;
    ptrBinOffset : ^DINT;
    NowOverflow : DINT;
    OverflowDelta : DINT;
    SetPos : DINT;
  END_STRUCT;
#pragma pack(pop)
  CntrFlgs : BDINT
  [
    1 InPosition,  //! <Type Comment="Axis is in position" Name="CntrFlgs.InPosition"/>
    2 FiltRdy,  //! <Type Comment="Axis is in position and jerk filter is ready" Name="CntrFlgs.FiltRdy"/>
    3 PosLimActive,  //! <Type Comment="Position limit is active, set position is over the SW end position" Name="CntrFlgs.PosLimActive"/>
    4 Decell,  //! <Type Comment="Deceleration is active" Name="CntrFlgs.Decell"/>
    5 bDynSWLimit,  //! <Type Comment="Set if axis has reached one of its dynamic SW endpositions" Name="CntrFlgs.bDynSWLimit"/>
    7 SetFlg,  //! <Type Comment="Set by calling the SetPositon, CNCRefRun and NCRefRun functions Reset after activating the controller." Name="CntrFlgs.SetFlg"/>
    10 EnLesFlg,  //! <Type Comment="Endless positioning is active" Name="CntrFlgs.EnLesFlg"/>
    11 DirFlg,  //! <Type Comment="Commanded axis direction (0 -&gt; positive, 1 -&gt; negative)" Name="CntrFlgs.DirFlg"/>
    12 ActDirFlg,  //! <Type Comment="Actual axis direction (0 -&gt; positive, 1 -&gt; negative)" Name="CntrFlgs.ActDirFlg"/>
    13 EmergStop,  //! <Type Comment="Emergency stop is active" Name="CntrFlgs.EmergStop"/>
    14 AutoRun,  //! <Type Comment="Controller output autotuning is running" Name="CntrFlgs.AutoRun"/>
    15 AutoStop,  //! <Type Comment="Controller output autotuning is ready" Name="CntrFlgs.AutoStop"/>
    16 Test,  //! <Type Comment="Is only queried when ControllerOn is set to 0." Name="CntrFlgs.Test"/>
    17 NoActpos,  //! <Type Comment="The Client &quot;iActPosition&quot; is not connected" Name="CntrFlgs.NoActpos"/>
    18 Overflow,  //! <Type Comment="The axis has an internal position overflow." Name="CntrFlgs.Overflow"/>
    19 NoControl,  //! <Type Comment="The axis is not connected to a controller and the CNC therefore operates as a profile generator only." Name="CntrFlgs.NoControl"/>
    20 ModuloFlg,  //! <Type Comment="The axis is defined as a modulo axis." Name="CntrFlgs.ModuloFlg"/>
    21 NoActPosMeth,  //! <Type Comment="The &quot;iActPosition&quot; client is not connected to a server (axis operates without posi-tion feedback)." Name="CntrFlgs.NoActPosMeth"/>
    22 NoRefMeth,  //! <Type Comment="The &quot;iRefChannal&quot; is not connected" Name="CntrFlgs.NoRefMeth"/>
    23 NoControlMeth,  //! <Type Comment="The &quot;oSignalchannal&quot; client is not connected" Name="CntrFlgs.NoControlMeth"/>
    24 NoSpecial,  //! <Type Comment="The &quot;oPrecyclictrigger&quot; client is not connected" Name="CntrFlgs.NoSpecial"/>
    25 NCMotion,  //! <Type Comment="The CNC class is operated in NC mode" Name="CntrFlgs.NCMotion"/>
    26 NoActPosChk,
  ];
#pragma pack(push, 1)
  Counter1 : STRUCT
    i : DINT;
    CounterPos : DINT;
    CounterBoxlength : DINT;
    EncoderOLD : DINT;
    Dist2Boxen : DINT;
    SpeedCalc : DINT;
    TelCalc : DINT;
    Timer1 : UDINT;
    NogTeProduceren : DINT;
    NogTeProdBuffer : ARRAY [0..10] OF DINT;
    wijzer : DINT;
    Timer : UDINT;
    CaseNogTeProd : DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  CurveTable : STRUCT  //! <Type Comment="Table curve points (Masterpos, Slavepos)" Name="CurveTable"/>
    MasterPos : DINT;  //! <Type Comment="Master axis position [Application units]" Name="CurveTable.MasterPos"/>
    SlavePos : DINT;  //! <Type Comment="Slave axis position [Application units]" Name="CurveTable.SlavePos"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  Curve : STRUCT  //! <Type Comment="Motion type curve data" Name="Curve"/>
    modulo : DINT;  //! <Type Comment="Lead axis modulo value" Name="Curve.modulo"/>
    tabellenth : DINT;  //! <Type Comment="number of curve points" Name="Curve.tabellenth"/>
    mul : DINT;  //! <Type Comment="Part of the transmission ratio" Name="Curve.mul"/>
    div : DINT;  //! <Type Comment="Part of the transmission ratio" Name="Curve.div"/>
    offset : DINT;  //! <Type Comment="Position offset" Name="Curve.offset"/>
    table : ARRAY [0..256] OF CurveTable;  //! <Type Comment="Table curve points (Masterpos, Slavepos)" Name="Curve.table"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  EEData : STRUCT
    dOffEE : DINT;
    dMulEE : DINT;
    dDivEE : DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  Encoder1 : STRUCT
    EncoderDelta : DINT;
    EncoderOld : DINT;
    SpeedDelta : DINT;
    Buffer : ARRAY [0..100] OF DINT;
    SpeedDeltaFilter : DINT;
    ii : DINT;
    FilterTotaal : DINT;
    Filter : DINT;
    Multi : DINT;
    Divider : DINT;
    i : DINT;
    EncPerCycle : DINT;
    Encx10000 : DINT;
    EncResolutie : DINT;
    SpeedMMper50Ms : DINT;
    Meting1 : DINT;
    Meting2 : DINT;
    enccalc1 : DINT;
    enccalc2 : DINT;
    enccalc3 : DINT;
    encdiv : DINT;
    encmul : DINT;
  END_STRUCT;
#pragma pack(pop)
  FeSetup : BDINT
  [
    1 Valid,  //! <Type Comment="must be 1 to Start FileEx work" Name="FeSetup.Valid"/>
    2 FileorRam,  //! <Type Comment="0= work in File 1= Work File" Name="FeSetup.FileorRam"/>
    3 EnableChecksum,  //! <Type Comment="0=no Checksum; 1=Calculate Checksum, increased write access on the CF card" Name="FeSetup.EnableChecksum"/>
    4 Encrypt,  //! <Type Comment="0=no encryption; 1=encrypt file, increased write access on the CF card" Name="FeSetup.Encrypt"/>
  ];
  IO_FLAG : BINT  //! <Type Comment="Status Flag für IO Daten" Name="IO_FLAG"/>
  [
    1 WrongHW,  //! <Type Comment="Falsche Hardware verbunden" Name="IO_FLAG.WrongHW"/>
    2 NoHW,  //! <Type Comment="Keine Hardware verbunden" Name="IO_FLAG.NoHW"/>
    3 NoCalibration,  //! <Type Comment="Keine Kalibrierungsdaten im Modul-EEPROM" Name="IO_FLAG.NoCalibration"/>
    4 ParaChkWrong,  //! <Type Comment="Die Parameter-Checksumme ist falsch" Name="IO_FLAG.ParaChkWrong"/>
    5 PhysicHiLimit,  //! <Type Comment="IO ist am oberen physikalischen Limit" Name="IO_FLAG.PhysicHiLimit"/>
    6 PhysicLoLimit,  //! <Type Comment="IO ist am unteren physikalischen Limit" Name="IO_FLAG.PhysicLoLimit"/>
    7 Invert,  //! <Type Comment="Daten sind invertiert" Name="IO_FLAG.Invert"/>
    14 OnDummyMode,  //! <Type Comment="1 = Objekt ist im Dummymodus (nicht refreshed)" Name="IO_FLAG.OnDummyMode"/>
    15 NotConnected,  //! <Type Comment="1 = Objekt ist nicht verbunden" Name="IO_FLAG.NotConnected"/>
    16 PhysicAccessOff,  //! <Type Comment="1 = kein physikalischer Zugriff erlaubt" Name="IO_FLAG.PhysicAccessOff"/>
  ];
#pragma pack(push, 1)
  IO_State : STRUCT
    uiIO_Flags : IO_FLAG;
    uiChNo : UINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  Jam : STRUCT
    Jamdetect : ARRAY [0..3] OF DINT;
    JamPos : ARRAY [0..3] OF DINT;
    JamDetection : ARRAY [0..3] OF DINT;
    SExtraBox : DINT;
    i : DINT;
    CaseJam : ARRAY [0..3] OF DINT;
    JamBoxlength : ARRAY [0..3] OF DINT;
    Boxlength : ARRAY [0..3] OF DINT;
    OldBoxlength : ARRAY [0..3] OF DINT;
  END_STRUCT;
#pragma pack(pop)
  MasterStruct : STRUCT  //! <Type Comment="Pointers to the master axis data" Name="MasterStruct"/>
    pos : ^DINT;  //! <Type Comment="Pointer to the master axis position" Name="MasterStruct.pos"/>
    Speed : ^DINT;  //! <Type Comment="Pointer to the master axis speed" Name="MasterStruct.Speed"/>
    ModuloMaster : ^DINT;  //! <Type Comment="Pointer to ModuloInt of master axis" Name="MasterStruct.ModuloMaster"/>
  END_STRUCT;
  pHwBase : ^HwBase;
  pHwBaseCDIAS : ^HwBaseCDIAS;
  RefMode : BDINT  //! <Type Comment="Motion Reference type" Name="RefMode"/>
  [
    1 No_Z_Input,  //! <Type Comment="0 --&gt; Referencing with referencing impuls&#13;&#10;1 --&gt; Referencing without referencing impuls&#13;&#10;" Name="RefMode.No_Z_Input"/>
    2 No_ES,  //! <Type Comment="0 --&gt; Referencing with endswitches&#13;&#10;1 --&gt; Referencing without endswitches" Name="RefMode.No_ES"/>
    3 Ref_direction,  //! <Type Comment="1 --&gt; Referencing on positive direction&#13;&#10;0 --&gt; Referencing on negative direction" Name="RefMode.Ref_direction"/>
    4 No_turnOnRefSw,  //! <Type Comment="0 --&gt; Reverse direction at the reference switch&#13;&#10;1 --&gt; Do not reverse direction at the reference switch" Name="RefMode.No_turnOnRefSw"/>
    5 No_turnOnESSw,  //! <Type Comment="0 --&gt; Reverse direction at the end switch&#13;&#10;1 --&gt; Do not reverse direction at the end switch" Name="RefMode.No_turnOnESSw"/>
    6 ESequalRef,  //! <Type Comment="1 --&gt; End switch as Reference switch is used&#13;&#10;" Name="RefMode.ESequalRef"/>
    7 StandardRef,  //! <Type Comment="0 --&gt; default reference mode&#13;&#10;1 --&gt; userdefined reference mode" Name="RefMode.StandardRef"/>
    8 NoSet,  //! <Type Comment="0 --&gt; The transmitted position is the reference position&#13;&#10;1 --&gt; The actual position is the reference position" Name="RefMode.NoSet"/>
    9 RefLatchPos,  //! <Type Comment="1 --&gt; Read reference position from client cLatchPos. If value changes, do a MoveAbsolute(cLatchPos) and set cLatchPos as current position." Name="RefMode.RefLatchPos"/>
  ];
  ringbuffer : ARRAY [0..16] OF DINT;
  SafetyConfigStateType :
  (
    _ModuleNotFound,
    _SafetyClassOK,
    _ReinitConfig,
    _UnsafeVarNotFound,
    _ModFromCfgNotFound,
    _MemAllocFailed,
    _ReadFWVerFailed,
    _UnknownCfgError,
    _WaitForSynchronicity,
    _AsyncComError:=9,
    _DOsIncreasedRestartApp:=10
  )$UDINT;
#pragma pack(push, 1)
  SafetyDiagInfo : STRUCT
    uControllerID : USINT;  //! <Type Comment="ID of µController (0 = µC1, else µC2)" Name="SafetyDiagInfo.uControllerID"/>
    ActErrorCode : USINT;  //! <Type Comment="actual error code" Name="SafetyDiagInfo.ActErrorCode"/>
    FirstErrorCode : USINT;  //! <Type Comment="code of first error that lead to an error state" Name="SafetyDiagInfo.FirstErrorCode"/>
    ReasonCode0 : UDINT;  //! <Type Comment="reason for error (meaning depends on actual error code)" Name="SafetyDiagInfo.ReasonCode0"/>
    ReasonCode1 : UDINT;  //! <Type Comment="reason for error (meaning depends on actual error code)" Name="SafetyDiagInfo.ReasonCode1"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  SafetyDiagState : STRUCT
    RunState : USINT;  //! <Type Comment=" 1..POST&#13;&#10; 2..SERVICE&#13;&#10; 4..ERROR&#13;&#10; 8..IDLE&#13;&#10;16..CHK_CFG&#13;&#10;32..OP_TEMP&#13;&#10;64..OP" Name="SafetyDiagState.RunState"/>
    ConfigState : USINT;  //! <Type Comment=" 1..INVALID&#13;&#10; 2..NOT_CONFIGURED&#13;&#10; 4..CONFIGURED_NOT_DEPLOYED_NOT_VERIFIED&#13;&#10; 8..CONFIGURED_AND_VERIFIED&#13;&#10;16..CONFIGURED_DEPLOYED_NOT_VERIFIED&#13;&#10;36..CONFIGURED_NOT_DEPLOYED_NOT_VERIFIED_DEV&#13;&#10;48..CONFIGURED_DEPLOYED_NOT_VERIFIED_DEV" Name="SafetyDiagState.ConfigState"/>
    LoginLevel : USINT;  //! <Type Comment="0..not logged in&#13;&#10;1..debug&#13;&#10;2..configuration&#13;&#10;3..general" Name="SafetyDiagState.LoginLevel"/>
    ErrorCounterIOState : UINT;  //! <Type Comment="Is increased on change of the error state of any input or output" Name="SafetyDiagState.ErrorCounterIOState"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  SensorLR : STRUCT
    MinimaleSpot : DINT;
    MinimaleCounter : ARRAY [0..3] OF DINT;
    MinimaalSSW : ARRAY [0..3] OF DINT;
    DiHW : ARRAY [0..3] OF DINT;
    Din : ARRAY [0..3] OF DINT;
    i : DINT;
  END_STRUCT;
#pragma pack(pop)
  t_e_VaranErrors :
  (
    _ClassOk,
    _NotInitialized,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._NotInitialized"/>
    _CallBackError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._CallBackError"/>
    _RequiredError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._RequiredError"/>
    _RootError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._RootError"/>
    _NoHardware,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._NoHardware"/>
    _WrongHardware,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._WrongHardware"/>
    _CreateDOFailed,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._CreateDOFailed"/>
    _DirectAccessFailed,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._DirectAccessFailed"/>
    _PllError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._PllError"/>
    _TimeoutInInit,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._TimeoutInInit"/>
    _HardwareRequiredIRQ,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._HardwareRequiredIRQ"/>
    _HardwareNotRequiredIRQ,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._HardwareNotRequiredIRQ"/>
    _HardwareFatalErrorIRQ,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._HardwareFatalErrorIRQ"/>
    _ManagerError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._ManagerError"/>
    _DisableError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._DisableError"/>
    _EnableError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._EnableError"/>
    _MultipleError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._MultipleError"/>
    _SPIError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._SPIError"/>
    _ErrorBootImageFPGA,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._ErrorBootImageFPGA"/>
    _NoCDIASInterface,  //! <Type Comment="for CIV class" Name="t_e_VaranErrors._NoCDIASInterface"/>
    _EEPromError,  //! <Type Comment="for CIV class" Name="t_e_VaranErrors._EEPromError"/>
    _NoVaranInterface,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._NoVaranInterface"/>
    _MemoryFault,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._MemoryFault"/>
    _TimesliceError,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._TimesliceError"/>
    _TimesliceErrorIRQ,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._TimesliceErrorIRQ"/>
    _WatchdogError,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._WatchdogError"/>
    _VaranTimeError,  //! <Type Comment="for HwControl class" Name="t_e_VaranErrors._VaranTimeError"/>
    _DiasTimeError,  //! <Type Comment="for HwControl class" Name="t_e_VaranErrors._DiasTimeError"/>
    _DORamFull,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DORamFull"/>
    _PortNoLink,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._PortNoLink"/>
    _VaranDriverNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._VaranDriverNotExists"/>
    _WrongDOLType,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._WrongDOLType"/>
    _WrongRunStatus,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._WrongRunStatus"/>
    _DOHandleInvalid,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DOHandleInvalid"/>
    _DOCmdInvalid,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DOCmdInvalid"/>
    _ManagerNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ManagerNotExists"/>
    _DOLAddressInvalid,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DOLAddressInvalid"/>
    _UnknownCommand,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._UnknownCommand"/>
    _ComponentNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ComponentNotExists"/>
    _ClientNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ClientNotExists"/>
    _CdiasEEPromNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CdiasEEPromNotExists"/>
    _CdiasEEPromNoGrant,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CdiasEEPromNoGrant"/>
    _CdiasEEPromNack,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CdiasEEPromNack"/>
    _PortNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._PortNotExists"/>
    _PortIsUplink,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._PortIsUplink"/>
    _NoMutex,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoMutex"/>
    _NoTask,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoTask"/>
    _IDNotFound,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._IDNotFound"/>
    _IDNotInitialized,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._IDNotInitialized"/>
    _InvalidDeviceAddress,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._InvalidDeviceAddress"/>
    _CallbackNotHandled,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CallbackNotHandled"/>
    _NoMem,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoMem"/>
    _NoLegacyWd,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoLegacyWd"/>
    _AdminDOLExecutionError,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._AdminDOLExecutionError"/>
    _DADOLExecutionError,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DADOLExecutionError"/>
    _SPIFlashNoAccess,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._SPIFlashNoAccess"/>
    _ClientNotready,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ClientNotready"/>
    _TimeoutVaran,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._TimeoutVaran"/>
    _UnknownFault,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._UnknownFault"/>
    _DiasError,  //! <Type Comment="for CIC/DIV with Dias" Name="t_e_VaranErrors._DiasError"/>
    _DeviceError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._DeviceError"/>
    _VaranTimeWarning,
    _OnlyASYSupported,
    _InvalidSerialNo,
    _CDIASRequiredError,
    _DIASRequiredError,
    _NoCalibDataFound,
    _ModuleFoundButManagerIsOff:=68,
    _InvalidConfguration,
    _ClientDisabled,
    _ClientCantEnable,
    _CdiasAddressInvalid,
    _SPIFlashInvalid,
    _SPIDOLIDInvalid,
    _SPIDOLInvalid,
    _SPIRequiredListError,
    _SPIChksumError,
    _ParameterInvalid,
    _DOTypeNotSupported,
    _DMAError,
    _PropertyIDInvalid,
    _PropertyValueInvalid,
    _DONumberOverflow,
    _APIUsageNotAllowed,
    _NodeTypeWrong,
    _DataLengthInvalid,
    _DOTypeInvalid,
    _OperationNotAllowed,
    _NodeNumberOverflow,
    _NoHandleFound
  )$UDINT;
#pragma pack(push, 1)
  t_s_ModulInfo : STRUCT
    Kennung : HINT;
    p_This : ^void;
  END_STRUCT;
#pragma pack(pop)
  tDoosnaam :
  (
    No_box:=0,
    Langsnaad:=1,
    Driepunt:=2,
    Driepunt_Vakverdeling:=3,
    Vierpunt_Infold:=4,
    Vierpunt_Outfold:=5,
    Vierpunt_Deksel:=6,
    Vierpunt_Dubbele_Wand:=7,
    Zespunt_In_In:=8,
    Zespunt_In_Out:=9,
    Zespunt_In_In_Gespiegeld:=10,
    Driepunt_Gespiegeld:=11,
    Langsnaad2:=12,
    Driepunt2:=13
  )$UDINT;
#pragma pack(push, 1)
  tDoosParametersMinMax : STRUCT
    Max_Invoer_Lengte : DINT;
    BoxMogelijk : BOOL;
    Max_Invoer_Breedte : DINT;
    T_Max : DINT;
    T_Min : DINT;
    U_Max : DINT;
    U_Min : DINT;
    V_Max : DINT;
    V_Min : DINT;
    W_Max : DINT;
    W_Min : DINT;
    X_Max : DINT;
    X_Min : DINT;
    Y_Max : DINT;
    Y_Min : DINT;
    Z_Max : DINT;
    Z_Min : DINT;
    Offset_Max : DINT;
    Offset_Min : DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  tDoosParameters : STRUCT
    Doostype : DINT;
    T : DINT;
    U : DINT;
    V : DINT;
    W : DINT;
    X : DINT;
    Y : DINT;
    Z : DINT;
    Offset : DINT;
    MinMax : ARRAY [1..14] OF tDoosParametersMinMax;
  END_STRUCT;
#pragma pack(pop)
  TextString : ARRAY [0..50] OF CHAR;
#pragma pack(push, 1)
  tHaak : STRUCT
    CaseRing : DINT;
    Senpos : DINT;
    wrPoint : DINT;
    rdPoint : DINT;
    CaseAansturing : DINT;
    Spos : DINT;
    StartPos : DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  tJam : STRUCT
    Jamdetect : DINT;
    Jampos : DINT;
    Jamdetection : DINT;
    SExtraBox : DINT;
    CaseJam : DINT;
    JamBoxlength : DINT;
    Boxlength : DINT;
  END_STRUCT;
#pragma pack(pop)
  tJamStatus :
  (
    Turned_Off:=0,
    Normal_Operation:=1,
    No_Box_Detected:=2,
    Holes_Detected:=3,
    TeachIn_Ok,
    Jam_Detect,
    Box_Oversized:=6,
    No_Sensor_Configurated
  )$UDINT;
#pragma pack(push, 1)
  tJamDetect : STRUCT
    NrOfJamSensors : DINT;
    SectieNrInMachine : DINT;
    MinSpot : DINT;
    MinJamSpeed : DINT;
    sExtraBox : DINT;
    iEncMulti : DINT;
    iEncDiv : DINT;
    T_Doos : DINT;
    OnOff : ARRAY [0..16] OF DINT;
    SensorNrInMachine : ARRAY [0..16] OF DINT;
    JamBoxlength : ARRAY [0..16] OF DINT;
    TeachInLength : ARRAY [0..16] OF DINT;
    Status : ARRAY [0..16] OF tJamStatus;
    Sensor : ARRAY [0..16] OF DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  tKop : STRUCT
    Present : ARRAY [0..10] OF DINT;
    Sensor : ARRAY [0..10] OF DINT;
    SensorHW : ARRAY [0..10] OF DINT;
    OffsetL : ARRAY [0..10] OF DINT;
    OffsetR : ARRAY [0..10] OF DINT;
    OffsetSTR : ARRAY [0..10] OF DINT;
    TopkomInMs : ARRAY [0..10] OF DINT;
    TafvalInMs : ARRAY [0..10] OF DINT;
    Boxlengte : ARRAY [0..10] OF DINT;
    Start : ARRAY [0..10] OF DINT;
    Lengte : ARRAY [0..10] OF DINT;
    Error : ARRAY [0..10] OF DINT;
    MinSpeed : ARRAY [0..10] OF DINT;
    Test : ARRAY [0..10] OF DINT;
    Pakket1 : ARRAY [0..10] OF DINT;
    Pakket2 : ARRAY [0..10] OF DINT;
    Pakket1SET : ARRAY [0..10] OF DINT;
    Pakket2SET : ARRAY [0..10] OF DINT;
    OutputHW : ARRAY [0..10] OF DINT;
    OnOff : ARRAY [0..10] OF DINT;
    iType : ARRAY [0..10] OF DINT;
    i2SensorCNT : ARRAY [0..10] OF DINT;
    iBoxLengte_Max : ARRAY [0..10] OF DINT;
    iBoxLengte_Min : ARRAY [0..10] OF DINT;
    iStart_Max : ARRAY [0..10] OF DINT;
    iStart_Min : ARRAY [0..10] OF DINT;
    iLengte_Max : ARRAY [0..10] OF DINT;
    iLengte_Min : ARRAY [0..10] OF DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  tLine : STRUCT
    Master : DINT;
    Slave : DINT;
  END_STRUCT;
#pragma pack(pop)
  tModel :
  (
    m0000:=0,
    m1250:=1,
    m1450:=2,
    m1700:=3,
    m1900:=4,
    m2300:=5,
    m2800:=6
  )$UDINT;
#pragma pack(push, 1)
  tOspeed : STRUCT
    EncIn : DINT;
    EncOud : DINT;
    EncDelta : DINT;
  END_STRUCT;
#pragma pack(pop)
  TransTypes :
  (
    VOLT,
    POTI,
    THERMO_J,
    POTI_10V_UNI,
    POTI_10V_BI,
    POTI_5V_UNI,
    POTI_5V_BI
  )$UDINT;
  tSectie :
  (
    PreFeeder:=1,
    TriFeeder:=2,
    Feeder:=3,
    MAS:=4,
    Prefold:=5,
    A_Sectie:=6,
    B_Sectie:=7,
    C_Sectie:=8,
    FinalFold:=9,
    F_Unit:=10,
    Trombone:=11,
    ConveyorBand:=12
  )$UDINT;
#pragma pack(push, 1)
  tSensor : STRUCT
    MinimaleSpot : DINT;
    MinimaleCounter : DINT;
    MinimaalSSW : DINT;
    Din : DINT;
    DiHW : DINT;
    i : DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  tTabel : STRUCT
    length : DINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  tVouwhaakDATA : STRUCT
    Mask : DINT;
    MaskIngegeven : DINT;
    Lead : DINT;
    Klephoogte : DINT;
    Raakpunt : DINT;
    Raakpunt_Corr : DINT;
    Raakpunt_Corr_Max : DINT;
    Raakpunt_Corr_Min : DINT;
    Stoppunt : DINT;
    Stoppunt_Corr : DINT;
    Stoppunt_Corr_Max : DINT;
    Stoppunt_Corr_Min : DINT;
    Offset : DINT;
    Offset_Corr : DINT;
    Offset_Corr_Max : DINT;
    Offset_Corr_Min : DINT;
    Vrijloop : DINT;
    Vrijloop_Corr : DINT;
    Vrijloop_Corr_Max : DINT;
    Vrijloop_Corr_Min : DINT;
    Release : DINT;
    Release_Corr : DINT;
    Release_Corr_Max : DINT;
    Release_Corr_Min : DINT;
    Speedcorrectie : DINT;
    Speedcorrectie_Max : DINT;
    Speedcorrectie_Min : DINT;
    Grote_Kleine_Haak : DINT;
    iEncMul : DINT;
    iEncDiv : DINT;
    oSpeed : DINT;
    oSensorHW : DINT;
    oSensorZeroHW : DINT;
    oJamdet : DINT;
    iJamBoxlength : DINT;
    iJamReset : DINT;
    MinSpot : DINT;
    SExtraBox : DINT;
    OnOff : DINT;
    Motor_LR : DINT;
    WriteProt : DINT;
    iSensorOffsetGH : DINT;
    PapierlijnGH : DINT;
    RusthoekGH : DINT;
    DoorloopGH : DINT;
    iSensorOffsetKH : DINT;
    PapierlijnKH : DINT;
    DoorloopKH : DINT;
    RusthoekKH : DINT;
    Nulhoek : DINT;
    T1PD0 : DINT;
    T1PD1 : DINT;
    T1PD2 : DINT;
    T1PD3 : DINT;
    T1PD4 : DINT;
    T1PD5 : DINT;
    T2PD0 : DINT;
    T2PD1 : DINT;
    T2PD2 : DINT;
    T2PD3 : DINT;
    T2PD4 : DINT;
    T2PD5 : DINT;
    Mask_Max : DINT;
    Mask_Min : DINT;
    Lead_Max : DINT;
    Lead_Min : DINT;
    Klephoogte_Max : DINT;
    Klephoogte_Min : DINT;
    iJamBoxlength_Max : DINT;
    iJamBoxlength_Min : DINT;
    iPosZeroOffset : DINT;
    FeedbackMotor : DINT;
  END_STRUCT;
#pragma pack(pop)
END_TYPE
